config/routes.rb
Rails.application.routes.draw do
  mount API => '/'
  root to: 'web/home#index'
  namespace :web do
    root 'base#verify', via: [:get, :post]
    get 'home', to: 'home#index', as: :home
    get 'follow', to: 'home#follow', as: :follow
    get 'restore', to: 'home#restore', as: :restore
    resources :travels do
      resources :deals
      new do
        get :set_destinations
      end
      collection do
        get :owned
      end
    end
    resources :deals do
      collection do
        get :owned
      end
      member do
        get :buy_form
        patch :buy
        put :abort
      end
    end
    get 'force_sign_in', to: 'sessions#force_new', as: :force_sign_in
    post 'force_sign_in', to: 'sessions#force_create'
    post 'force_sign_up', to: 'users#create_faker', as: :force_sign_up
    get 'sign_in', to: 'sessions#create', as: :sign_in
    get 'sign_out', to: 'sessions#destroy', as: :sign_out
    resources :errors do
      collection do
        get :error_404
        get :error_500
      end
    end
    unless Rails.application.config.consider_all_requests_local
      get '*not_found', to: 'errors#error_404'
    end
  end
end

app/models/travel.rb
class Travel < ActiveRecord::Base
  include Identifierable, AASM
  belongs_to :user
  belongs_to :country
  has_many :destinations
  has_many :deals
  default_scope { includes(:deals) }
  aasm column: 'state' do
    state :preparing, initial: true
    state :departured
    state :returned
    event :departure do
      transitions from: :preparing, to: :departured
    end
    event :return do
      transitions from: :departured, to: :returned
    end
  end
  validates :departure_at, presence: true
  validates :return_at, presence: true

  def set_destinations! countries
    countries.each do |country|
      self.destinations.create!(country: country)
    end
  end
end

app/controllers/web/travels_controller.rb
# -*- encoding : utf-8 -*-
class Web::TravelsController < Web::BaseController
  before_action :find_travel, only: %w(show edit update)
  skip_before_action :check_follower, only: %w(show)
  
  def index
    @travels = @current_user.travels.page(params[:page])
  end
  
  def show
    if @travel.user.id == @current_user.id
      @deals = @travel.deals.order("FIELD(state, 'in_process', 'success', 'failure')").order(created_at: :desc)
      @handled_deals_count, @total_deals_count = @deals.select{|deal| !deal.in_process?}.count, @deals.count
      @completion = ((@handled_deals_count.to_f / @total_deals_count.to_f) * 100)
      @completion = @completion.nan? ? 0 : @completion.round
      render 'traveller_show'
    else
      set_previous_path
      render 'buyer_show'
    end
  end

  def set_destinations
    @country_ids = params[:country_ids].try(:split, ',') || []
  end
  
  def new
    begin
      @travel = Travel.new
      raise ParameterIsEmpty.new if (@country_ids = params[:country_ids].try(:split, ',')).blank?
      @countries = Country.find(@country_ids)
    rescue ParameterIsEmpty
      (@travel = Travel.new).errors.add(:base, '至少选择一个国家或地区')
      render action: 'set_destinations'
    end
  end
  
  def edit
  end
  
  def create
    begin
      raise CountryIsEmpty.new if (@country_ids = params[:country_ids].try(:split, ',')).blank?
      @countries = [Country.find(@country_ids)].flatten
      @travel = @current_user.travels.new(travel_params)
      if @travel.save
        @travel.set_destinations!(@countries)
        redirect_to [:web, @travel]
      else
        render action: 'new'
      end
    rescue CountryIsEmpty
      (@travel = Travel.new).errors.add(:base, '至少选择一个国家或地区')
      render action: 'set_destinations'
    rescue ActiveRecord::RecordNotFound
      (@travel = Travel.new).errors.add(:base, '无效的国家或地区')
      render action: 'new'
    end
  end
  
  def update
    if @travel.update(travel_params)
      redirect_to @travel, notice: '操作成功！'
    else
      render action: 'edit'
    end
  end

  def owned
    @travels = @current_user.travels.order(created_at: :desc).page(params[:page])
  end

  protected
    def travel_params
      params.require(:travel).permit!
    end

    def find_travel
      @travel = Travel.find(params[:id])
    end
end

app/views/web/travels/buyer_show.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title"><%= @travel.user.nickname %>的行程</div>
    <a class="w-inline-block navbar-button" href="<%= url_for(owned_web_travels_path) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
  </div>
</div>
<div class="body">
  <div class="w-clearfix grey-header">
    <h2 class="grey-heading-title">TA的行程</h2>
  </div>
  <div class="w-clearfix travel-description padding">
    <%= image_tag(@travel.user.portrait.w100_h100_fl_q60.url || 'web/user_portrait.jpg', class: 'portrait') %>
    <div class="description">
      <p>您的微信好友<span class="strong"><%= @travel.user.nickname %></span>将于<span class="strong"><%= @travel.departure_at.strftime('%Y年%m月%d日') %></span>前往<span class="strong"><%= hr_travel_destinations(@travel.destinations)%></span>旅游，并于<span class="strong"><%= @travel.return_at.strftime('%Y年%m月%d日') %></span>回国，您现在可以在此发布代购需求。</p>
    </div>
  </div>
  <div class="w-clearfix grey-header">
    <h2 class="grey-heading-title">我的清单</h2>
  </div>
  <div class="w-clearfix travel-deals-list padding">
    <% if @travel.deals.blank? %>
    <div class="blank-notice"><p>清单是空的哦！</p></div>
    <% else %>
    <ul class="list list-events">
      <% @travel.deals.where(user_id: @current_user.id).order(created_at: :desc).each do |deal| %>
      <li class="list-calendar-events" data-ix="list-item">
        <a class="w-clearfix w-inline-block" href="<%= url_for([:web, deal])%>" data-load="1">
          <div class="calendar-col-left">
            <div class="event-title"><%= deal.content %></div>
            <div class="w-clearfix text-event-wrap">
              <div class="left-text-icon icon ion-pricetags"></div>
              <div class="event-text"><%= deal.quantity %>件</div>
              <div class="left-text-icon icon ion-calculator"></div>
              <div class="event-text"><%= hr_deal_acceptable_price(deal.acceptable_price) %></div>
              <% unless deal.photographs.blank? %>
              <div class="left-text-icon icon ion-images"></div>
              <div class="event-text">有图片</div>
              <% end %>
            </div>
          </div>
        </a>
      </li>
      <% end %>
    </ul>
    <% end %>
    <%= link_to '发布新需求', new_web_travel_deal_path(@travel), class: 'submit-button action-button' %>
  </div>
</div>

app/views/web/travels/dealed.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title">TA的行程</div>
    <a class="w-inline-block navbar-button" href="<%= url_for(web_home_path) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
  </div>
</div>
<div class="news-container">
  <ul class="w-clearfix list-news">
    <% @travels.each do |travel| %>
    <li class="list-item-new">
      <a class="w-inline-block link-blog-list" href="<%= url_for([:web, travel]) %>" data-load="1">
        <div class="image-new w-clearfix">
          <% if travel.deals.blank? %>
          #代购清单是空的
          <% else %>
          <% travel.deals.map(&:user).uniq.each do |user| %>
          <div class="profile">
            <%= image_tag(user.portrait.w100_h100_fl_q60.url) %>
            <div class="deals"><span class="icon ion-bag"></span> x <%= user.deals.count %></div>
          </div>
          <% end %>
          <% end %>
        </div>
        <div class="text-new">
          <div><span class="category-link">目的地</span><span class="description-new"><%= hr_travel_destinations(travel.destinations)%></span></div>
          <div><span class="category-link">出行日期</span><span class="description-new"><%= travel.departure_at.strftime('%Y年%m月%d日') %> - <%= travel.return_at.strftime('%m月%d日') %></span></div>
          <div><span class="category-link">状态</span><span class="description-new"><%= travel.aasm.human_state %></span></div>
        </div>
      </a> 
    </li>
    <% end %>
  </ul>
</div>
<div class="w-clearfix options-new less-padding-sides-blog border-top">
  <a class="w-clearfix w-inline-block small-button grey" href="#">
    <div class="icon-button bigger">
      <div class="icon ion-ios-arrow-left"></div>
    </div>
    <div class="text-button">上一页</div>
  </a>
  <a class="w-clearfix w-inline-block small-button grey last right" href="#">
    <div class="icon-button bigger">
      <div class="icon ion-ios-arrow-right"></div>
    </div>
    <div class="text-button">下一页</div>
  </a>
</div>

app/views/web/travels/new.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title">创建新行程 - 第2/2步</div>
    <a class="w-inline-block navbar-button" href="<%= url_for(set_destinations_new_web_travel_path(country_ids: @country_ids.join(','))) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
  </div>
</div>
<div class="body padding">
  <div class="w-form">
    <%= render "web/commons/error_messages", target: @travel %>
    <%= form_for [:web, @travel] do |f| %>
      <%= hidden_field_tag :country_ids, @country_ids.join(',') %>
      <div class="separator-fields"></div>
      <div class="separator-fields"></div>
      <div class="row-input-list">
        <div class="w-clearfix input-form one-line">
          <label class="label-form" for="birthday-field"><%= web_ar_t('travel.destinations') %></label>
          <div class="pt10"><%= @countries.map(&:zh_name).join('、') %></div>
        </div>
        <div class="separator-fields"></div>
      </div>
      <div class="row-input-list">
        <label class="label-form" for="travel_departure_at"><%= web_ar_t('travel.departure_at') %></label>
        <input type="date" id="travel_departure_at" name="travel[departure_at]" data-name="travel_departure_at" class="w-input input-form">
        <div class="separator-fields"></div>
      </div>
      <div class="row-input-list">
        <label class="label-form" for="travel_return_at"><%= web_ar_t('travel.return_at') %></label>
        <input type="date" id="travel_return_at" name="travel[return_at]" data-name="travel_return_at" class="w-input input-form">
        <div class="separator-fields"></div>
      </div>
      <div>
        <label class="label-form" for="message"><%= web_ar_t('travel.description') %></label>
        <textarea id="travel_description" name="travel[description]" data-name="travel_description" placeholder="#可以写一些行程方面具体的安排哦" class="w-input input-form textarea"></textarea>
      </div>
      <div class="separator-button-input"></div>
      <input type="submit" value="填写完成，提交" data-wait="请稍候..." class="w-button action-button"> 
    <% end %>
  </div>
</div>
<% content_for :javascript do %>
  <script>
    jQuery(document).ready(function(){
      $('#travel_departure_at').on('change', function() {
        var parts = $(this).val().split('-');
        var date = new Date(parts[0], parts[1] - 1, parts[2]);
        date.setDate(date.getDate() + 7);
        $('#travel_return_at').val(date.getFullYear() + '-' + (("0" + (date.getMonth() + 1))).slice(-2) + '-' + ("0" + date.getDate()).slice(-2));
      });
    });
  </script>
<% end %>

app/views/web/travels/others_show.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title"><%= @travel.user.nickname %>的行程</div>
    <a class="w-inline-block navbar-button" href="<%= url_for(owned_web_travels_path) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
  </div>
</div>
<div class="body">
  <div class="w-clearfix grey-header">
    <h2 class="grey-heading-title">TA的行程</h2>
  </div>
  <div class="w-clearfix travel-description padding">
    <%= image_tag(@travel.user.portrait.w100_h100_fl_q60.url || 'web/user_portrait.jpg', class: 'portrait') %>
    <div class="description">
      <p>您的微信好友<span class="strong"><%= @travel.user.nickname %></span>将于<span class="strong"><%= @travel.departure_at.strftime('%Y年%m月%d日') %></span>前往<span class="strong"><%= hr_travel_destinations(@travel.destinations)%></span>旅游，并于<span class="strong"><%= @travel.return_at.strftime('%Y年%m月%d日') %></span>回国，您现在可以在此发布代购需求。</p>
    </div>
  </div>
  <div class="w-clearfix grey-header">
    <h2 class="grey-heading-title">我的清单</h2>
  </div>
  <div class="w-clearfix travel-deals-list padding">
    <% if @travel.deals.blank? %>
    <div class="blank-notice"><p>清单是空的哦！</p></div>
    <% else %>
    <ul class="list list-events">
      <% @travel.deals.where(user_id: @current_user.id).order(created_at: :desc).each do |deal| %>
      <li class="list-calendar-events" data-ix="list-item">
        <a class="w-clearfix w-inline-block" href="<%= url_for([:web, deal])%>" data-load="1">
          <div class="calendar-col-left">
            <div class="event-title"><%= deal.content %></div>
            <div class="w-clearfix text-event-wrap">
              <div class="left-text-icon icon ion-pricetags"></div>
              <div class="event-text"><%= deal.quantity %>件</div>
              <div class="left-text-icon icon ion-calculator"></div>
              <div class="event-text"><%= hr_deal_acceptable_price(deal.acceptable_price) %></div>
              <% unless deal.photographs.blank? %>
              <div class="left-text-icon icon ion-images"></div>
              <div class="event-text">有图片</div>
              <% end %>
            </div>
          </div>
        </a>
      </li>
      <% end %>
    </ul>
    <% end %>
    <%= link_to '发布新需求', new_web_travel_deal_path(@travel), class: 'submit-button action-button' %>
  </div>
</div>

app/views/web/travels/owned.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title">我的行程</div>
    <a class="w-inline-block navbar-button" href="<%= url_for(web_home_path) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
  </div>
</div>
<div class="news-container">
  <ul class="w-clearfix list-news">
    <% @travels.each do |travel| %>
    <li class="list-item-new">
      <a class="w-inline-block link-blog-list" href="<%= url_for([:web, travel]) %>" data-load="1">
        <div class="image-new w-clearfix">
          <% if travel.deals.blank? %>
          #代购清单是空的
          <% else %>
          <% travel.deals.map(&:user).uniq.each do |user| %>
          <div class="profile">
            <%= image_tag(user.portrait.w100_h100_fl_q60.url) %>
            <div class="deals"><span class="icon ion-bag"></span> x <%= user.deals.count %></div>
          </div>
          <% end %>
          <% end %>
        </div>
        <div class="text-new">
          <div><span class="category-link">目的地</span><span class="description-new"><%= hr_travel_destinations(travel.destinations)%></span></div>
          <div><span class="category-link">出行日期</span><span class="description-new"><%= travel.departure_at.strftime('%Y年%m月%d日') %> - <%= travel.return_at.strftime('%m月%d日') %></span></div>
          <div><span class="category-link">状态</span><span class="description-new"><%= travel.aasm.human_state %></span></div>
        </div>
      </a> 
    </li>
    <% end %>
  </ul>
</div>
<div class="w-clearfix options-new less-padding-sides-blog border-top">
  <a class="w-clearfix w-inline-block small-button grey" href="#">
    <div class="icon-button bigger">
      <div class="icon ion-ios-arrow-left"></div>
    </div>
    <div class="text-button">上一页</div>
  </a>
  <a class="w-clearfix w-inline-block small-button grey last right" href="#">
    <div class="icon-button bigger">
      <div class="icon ion-ios-arrow-right"></div>
    </div>
    <div class="text-button">下一页</div>
  </a>
</div>

app/views/web/travels/owned_show.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title">查看行程</div>
    <a class="w-inline-block navbar-button" href="<%= url_for(owned_web_travels_path) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
    <a class="w-inline-block navbar-button right share-button" href="javascript:;">
      <div class="navbar-button-icon icon ion-ios-upload-outline"></div>
    </a>
  </div>
</div>
<div class="body">
  <div class="share-mask"><%= image_tag('web/share_mask.png') %></div>
  <div class="hero-image">
    <div class="hero-image-title">
      <h2>代购清单</h2>
      <div class="sub-title-small"><%= @handled_deals_count %> / <%= @total_deals_count %> 个任务 &nbsp;|&nbsp;&nbsp;已完成 <%= @completion %>%</div>
    </div>
    <div class="hero-image-img"><%= image_tag('web/travel_bg.jpg') %></div>
  </div>
  <% if @travel.deals.count.zero? %>
  <div class="empty-deal">
    <p>代购清单是空哒！快告诉朋友们吧~</p>
    <p>请点击右上角 <span class="icon ion-ios-more"></span> 按钮</p>
    <p>将此行程分享给微信好友或朋友圈</p>
  </div>
  <% else %>
  <ul class="list">
    <% @deals.each do |deal| %>
    <li class="list-item<%= " grey #{deal.state}" if !deal.in_process? %>">
      <a class="w-clearfix w-inline-block<%= " #{deal.state}" if !deal.in_process? %>" href="<%= url_for([:web, deal]) %>">
        <div class="icon-list<%= " #{deal.state}" if !deal.in_process? %>">
          <div class="icon <%= deal.failure? ? 'ion-ios-close-empty' : 'ion-ios-checkmark-empty' %>"></div>
        </div>
        <div class="title-list"><%= deal.content %></div>
        <%= image_tag(deal.user.portrait.w100_h100_fl_q60.url, class: 'portrait') %>
      </a>
    </li>
    <% end %>
  </ul>
  <% end %>
</div>
<% content_for :javascript do %>
  <%= javascript_include_tag 'http://res.wx.qq.com/open/js/jweixin-1.0.0.js' %>
  <script>
    jQuery(document).ready(function(){
      $('.share-button').on('click', function() {
        $('.share-mask').show();
      });

      $('.share-mask').on('click', function() {
        $('.share-mask').hide();
      });
    });
    <%= wechat_config_tag %>
    wx.ready(function(){
      wx.onMenuShareAppMessage({
        title: '我要粗去玩啦~有什么要带的吗',
        desc: '我在用#小信鸽#统计购物清单，快快点我来发布你的清单吧！',
        link: '<%= request.original_url %>',
        imgUrl: '<%= image_url(@travel.user.portrait.w180_h180_fl_q60.url) %>',
        type: 'link',
        dataUrl: '',
        success: function () { 
        },
        cancel: function () { 
        }
      });

      wx.onMenuShareTimeline({
        title: '我要粗去玩啦~有什么要带的吗',
        link: '<%= request.original_url %>',
        imgUrl: '<%= image_url(@travel.user.portrait.w180_h180_fl_q60.url) %>',
        success: function () { 
        },
        cancel: function () { 
        }
      });
    });
  </script>
<% end %>

app/views/web/travels/owner_show.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title">查看行程</div>
    <a class="w-inline-block navbar-button" href="<%= url_for(owned_web_travels_path) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
    <a class="w-inline-block navbar-button right share-button" href="javascript:;">
      <div class="navbar-button-icon icon ion-ios-upload-outline"></div>
    </a>
  </div>
</div>
<div class="body">
  <div class="share-mask"><%= image_tag('web/share_mask.png') %></div>
  <div class="hero-image">
    <div class="hero-image-title">
      <h2>代购清单</h2>
      <div class="sub-title-small"><%= @handled_deals_count %> / <%= @total_deals_count %> 个任务 &nbsp;|&nbsp;&nbsp;已完成 <%= @completion %>%</div>
    </div>
    <div class="hero-image-img"><%= image_tag('web/travel_bg.jpg') %></div>
  </div>
  <% if @travel.deals.count.zero? %>
  <div class="empty-deal">
    <p>代购清单是空哒！快告诉朋友们吧~</p>
    <p>请点击右上角 <span class="icon ion-ios-more"></span> 按钮</p>
    <p>将此行程分享给微信好友或朋友圈</p>
  </div>
  <% else %>
  <ul class="list">
    <% @deals.each do |deal| %>
    <li class="list-item<%= " grey #{deal.state}" if !deal.in_process? %>">
      <a class="w-clearfix w-inline-block<%= " #{deal.state}" if !deal.in_process? %>" href="<%= url_for([:web, deal]) %>">
        <div class="icon-list<%= " #{deal.state}" if !deal.in_process? %>">
          <div class="icon <%= deal.failure? ? 'ion-ios-close-empty' : 'ion-ios-checkmark-empty' %>"></div>
        </div>
        <div class="title-list"><%= deal.content %></div>
        <%= image_tag(deal.user.portrait.w100_h100_fl_q60.url, class: 'portrait') %>
      </a>
    </li>
    <% end %>
  </ul>
  <% end %>
</div>
<% content_for :javascript do %>
  <%= javascript_include_tag 'http://res.wx.qq.com/open/js/jweixin-1.0.0.js' %>
  <script>
    jQuery(document).ready(function(){
      $('.share-button').on('click', function() {
        $('.share-mask').show();
      });

      $('.share-mask').on('click', function() {
        $('.share-mask').hide();
      });
    });
    <%= wechat_config_tag %>
    wx.ready(function(){
      wx.onMenuShareAppMessage({
        title: '我要粗去玩啦~有什么要带的吗',
        desc: '我在用#小信鸽#统计购物清单，快快点我来发布你的清单吧！',
        link: '<%= request.original_url %>',
        imgUrl: '<%= image_url(@travel.user.portrait.w180_h180_fl_q60.url) %>',
        type: 'link',
        dataUrl: '',
        success: function () { 
        },
        cancel: function () { 
        }
      });

      wx.onMenuShareTimeline({
        title: '我要粗去玩啦~有什么要带的吗',
        link: '<%= request.original_url %>',
        imgUrl: '<%= image_url(@travel.user.portrait.w180_h180_fl_q60.url) %>',
        success: function () { 
        },
        cancel: function () { 
        }
      });
    });
  </script>
<% end %>

app/views/web/travels/set_destinations.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title">创建新行程 - 第1/2步</div>
    <a class="w-inline-block navbar-button" href="<%= url_for(web_home_path) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
  </div>
</div>
<div class="body">
  <div class="w-clearfix grey-header">
    <h2 class="grey-heading-title">请选择目的地</h2>
  </div>
  <div class="padding">
    <%= render "web/commons/error_messages", target: @travel %>
    <% Country.alphabetic.each_with_index do |country, i| %>
    <div class="country-item<%= ' last' if Country.alphabetic.count == i + 1 %>">
      <a class="w-clearfix w-inline-block" href="javascript:;">
        <div class="flag-image"><%= image_tag country.flag.w60_h40_fl_q100.url %></div>
        <div class="name"><h3><%= "#{PinYin.abbr(country.zh_name)[0].upcase} - #{country.zh_name} / #{country.en_name.truncate(18)}" %></h3></div>
        <div class="checkmark<%= ' w-hidden' if !@country_ids.include?(country.id.to_s) %>" data-id="<%= country.id %>"><span class="icon ion-checkmark-circled"></span></div>
      </a>
    </div>
    <% end %>
    <div class="separator-fields"></div>
    <div class="separator-fields"></div>
    <div class="w-form">
      <%= link_to '选择完成，下一步', new_web_travel_path, class: 'w-button action-button submit-button' %>
      <div class="separator-fields"></div>
      <div class="separator-fields"></div>
    </div>
  </div>
  </div>
</div>
<% content_for :javascript do %>
  <script>
    $(document).ready(function() {
      $('.country-item > a').click(function(e) {
        e.preventDefault();
        $(this).children('.checkmark').toggle();
      });

      $('.submit-button').click(function(e) {
        e.preventDefault();
        window.location = $(this).attr('href') + '?country_ids=' + $('.country-item > a > .checkmark:visible').map(function() {return $(this).data('id')}).get();
      });
    });
  </script>
<% end %>