config/routes.rb
Rails.application.routes.draw do
  mount API => '/'
  root to: 'web/home#index'
  namespace :web do
    root 'base#verify', via: [:get, :post]
    get 'home', to: 'home#index', as: :home
    get 'follow', to: 'home#follow', as: :follow
    get 'restore', to: 'home#restore', as: :restore
    resources :travels do
      resources :deals
      new do
        get :set_destinations
      end
      collection do
        get :owned
      end
    end
    resources :deals do
      collection do
        get :owned
      end
      member do
        get :buy_form
        patch :buy
        put :abort
      end
    end
    get 'force_sign_in', to: 'sessions#force_new', as: :force_sign_in
    post 'force_sign_in', to: 'sessions#force_create'
    post 'force_sign_up', to: 'users#create_faker', as: :force_sign_up
    get 'sign_in', to: 'sessions#create', as: :sign_in
    get 'sign_out', to: 'sessions#destroy', as: :sign_out
    resources :errors do
      collection do
        get :error_404
        get :error_500
      end
    end
    unless Rails.application.config.consider_all_requests_local
      get '*not_found', to: 'errors#error_404'
    end
  end
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  include Identifierable, AASM
  attr_accessor :photograph_media_ids, :acceptable_price_value, :acceptable_price_currency_id, :actual_price_value, :actual_price_currency_id
  belongs_to :travel
  belongs_to :user
  belongs_to :acceptable_price, class_name: 'Price', dependent: :destroy
  belongs_to :actual_price, class_name: 'Price', dependent: :destroy
  has_many :photographs, class_name: 'DealPhotograph'
  before_create :set_acceptable_price
  after_create :set_photographs
  aasm column: 'state' do
    state :pending
    state :in_process, initial: true
    state :success
    state :failure
    event :agree do
      transitions from: :pending, to: :in_process
    end
    event :finish do
      transitions from: :in_process, to: :success
    end
    event :abort do
      transitions from: :in_process, to: :failure
    end
    event :disagree do
      transitions from: :pending, to: :declined
    end
  end
  validates :content, presence: true
  validates :expected_quantity, presence: true

  def update_acceptable_price!
    self.acceptable_price.try(:destroy!)
    self.set_acceptable_price
    self.save!
  end

  def buy attributes
    actual_price_value = attributes[:actual_price_value].to_f
    actual_price_currency = Currency.find(attributes[:actual_price_currency_id])
    unless self.acceptable_price.blank?
      if self.acceptable_price.currency.blank?
        raise UnacceptablePrice.new if actual_price_currency.exchange_to_local(actual_price_value) > self.acceptable_price.in_local
      else
        raise DifferentCurrency.new if actual_price_currency.id != self.acceptable_price.currency.id
        raise UnacceptablePrice.new if actual_price_value > self.acceptable_price.in_foreign
      end
    end
    self.update!(attributes.merge(actual_price: Price.create!(currency: actual_price_currency, raw_value: actual_price_value)))
    self.finish!
  end

  protected
    def set_photographs
      photograph_media_ids.each do |photograph_media_id|
        self.photographs.create_with_wechat!(type: :sample, media_id: photograph_media_id)
      end unless photograph_media_ids.blank?
    end

    def set_acceptable_price
      self.acceptable_price = Price.create!(currency: Currency.where(id: self.acceptable_price_currency_id).first, raw_value: self.acceptable_price_value) unless self.acceptable_price_value.blank?
    end
end

app/controllers/web/deals_controller.rb
# -*- encoding : utf-8 -*-
class Web::DealsController < Web::BaseController
  before_action :find_deal, only: %w(show edit update destroy buy_form buy abort)
  before_action :find_travel, only: %w(new create)
  
  def index
    @deals = @current_user.deals.page(params[:page])
  end
  
  def show
    if @deal.user.id == @current_user.id
      render 'buyer_show'
    else
      render 'traveller_show'
    end
  end
  
  def new
    @deal = Deal.new
  end
  
  def edit
  end
  
  def create
    @deal = @current_user.deals.new(deal_params.merge(travel: @travel))
    if @deal.save
      redirect_to [:web, @deal.travel]
    else
      render action: 'new'
    end
  end
  
  def update
    if @deal.update(deal_params)
      @deal.update_acceptable_price!
      redirect_to [:web, @deal.travel]
    else
      
    end
  end

  def destroy
    @deal.destroy
    redirect_to [:web, @deal.travel]
  end

  def owned
    @deals = @current_user.deals.order(created_at: :desc).page(params[:page])
  end

  def buy_form
  end

  def buy
    begin
      raise InvalidActualPriceCurrency.new if deal_params[:actual_price_currency_id].blank?
      actual_price_value = deal_params[:actual_price_value].try(:to_f)
      raise InvalidActualPrice.new if actual_price_value.blank? or actual_price_value <= 0
      @deal.buy(deal_params)
      redirect_to [:web, @deal.travel]
    rescue InvalidActualPriceCurrency
      @deal.errors.add(:base, '请选择货币种类')
      render action: 'buy_form'
    rescue InvalidActualPrice
      @deal.errors.add(:base, '请填写实际购买价格')
      render action: 'buy_form'
    rescue DifferentCurrency
      @deal.errors.add(:base, '请选择正确的货币种类')
      render action: 'buy_form'
    rescue UnacceptablePrice
      @deal.errors.add(:base, '实际价格不能高于可接受价格')
      render action: 'buy_form'
    end
  end

  def abort
    @deal.abort!
    redirect_to [:web, @deal.travel]
  end

  protected
    def deal_params
      params.require(:deal).permit!
    end

    def find_deal
      @deal = (@current_user.deals.where(id: params[:id]).first || Deal.where(travel_id: @current_user.travels.map(&:id)).where(id: params[:id]).first || raise(ActiveRecord::RecordNotFound))
    end

    def find_travel
      @travel = Travel.find(params[:travel_id])
    end
end

app/views/web/deals/buy_form.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title">确认购买</div>
    <a class="w-inline-block navbar-button" href="<%= url_for([:web, @deal]) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
  </div>
</div>
<div class="body padding">
  <div class="w-form">
    <%= render "web/commons/error_messages", target: @deal %>
    <%= form_for [:web, @deal], url: buy_web_deal_path(@deal) do |f| %>
      <div class="separator-fields"></div>
      <div class="separator-fields"></div>
      <div class="row-input-list">
        <label class="label-form" for="deal_content"><%= web_ar_t('deal.content') %></label>
        <div class="value-form"><%= @deal.content %></div>
        <div class="separator-fields"></div>
      </div>
      <div class="row-input-list">
        <label class="label-form" for="deal_expected_quantity"><%= web_ar_t('deal.expected_quantity') %></label>
        <div class="value-form"><%= @deal.expected_quantity %>件</div>
        <div class="separator-fields"></div>
      </div>
      <div class="row-input-list">
        <label class="label-form" for="deal_acceptable_price_value"><%= web_ar_t('deal.acceptable_price_value') %></label>
        <div class="value-form"><%= hr_deal_acceptable_price(@deal.acceptable_price, with_local: true) %></div>
        <div class="separator-fields"></div>
      </div>
      <div class="row-input-list">
        <label class="label-form" for="deal_expected_quantity"><%= web_ar_t('deal.actual_quantity') %></label>
        <select id="deal_actual_quantity" name="deal[actual_quantity]" class="w-select input-form select">
          <% 1.upto(@deal.expected_quantity).each do |actual_quantity| %>
          <option value="<%= actual_quantity %>"<%= ' selected' if actual_quantity == @deal.expected_quantity %>><%= actual_quantity %>件</option>
          <% end %>
        </select>
        <div class="separator-fields"></div>
      </div>
      <div class="row-input-list">
        <label class="label-form" for="deal_actual_price_value"><%= web_ar_t('deal.actual_price_value') %></label>
        <div class="w-row">
          <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 n-p-l">
            <input type="text" id="deal_actual_price_value" name="deal[actual_price_value]" data-name="deal_actual_price_value" class="w-input input-form">
          </div>
          <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 n-p-r">
            <select id="deal_actual_price_currency_id" name="deal[actual_price_currency_id]" class="w-select input-form select">
              <% if @deal.acceptable_price.try(:currency).blank? %>
              <% Currency.circulation_in(@deal.travel.destinations).each do |currency| %>
              <option value="<%= currency.id %>"<%= ' selected' if currency.id == @deal.acceptable_price.try(:currency).try(:id) %>><%= currency.name_with_code %></option>
              <% end %>
              <% else %>
              <option value="<%= @deal.acceptable_price.currency.id %>" selected><%= @deal.acceptable_price.currency.name_with_code %></option>
              <% end %>
            </select>
          </div>
        </div>
      </div>
      <div class="separator-button-input"></div>
      <input type="submit" value="确认购买" data-wait="请稍候..." class="w-button action-button"> 
    <% end %>
  </div>
</div>

app/views/web/deals/buyer_show.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title">需求详情</div>
    <a class="w-inline-block navbar-button" href="<%= params[:from] == 'owned_deals' ? url_for(owned_web_deals_path) : url_for([:web, @deal.travel]) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
  </div>
</div>
<div class="body padding">
  <div class="w-form">
    <%= render "web/commons/error_messages", target: @deal %>
    <%= form_tag nil do %>
      <div class="separator-fields"></div>
      <div class="separator-fields"></div>
      <div class="row-input-list">
        <label class="label-form" for="deal_content"><%= web_ar_t('deal.content') %></label>
        <div class="value-form"><%= @deal.content %></div>
        <div class="separator-fields"></div>
      </div>
      <% unless @deal.photographs.blank? %>
      <div class="row-input-list">
        <label class="label-form" for="deal_expected_quantity"><%= web_ar_t('deal.photographs') %></label>
        <div class="value-form">
          <div class="image-preview">
            <% @deal.photographs.each do |photograph| %>
            <div class="nailthumb-container image-thumbnail" data-origin-url="<%= photograph.file.url %>"><%= image_tag(photograph.file.w100_h100_fl_q60.url) %></div>
            <% end %>
          </div>
        </div>
        <div class="separator-fields"></div>
      </div>
      <% end %>
      <div class="row-input-list">
        <label class="label-form" for="deal_expected_quantity"><%= web_ar_t('deal.expected_quantity') %></label>
        <div class="value-form"><%= @deal.expected_quantity %>件</div>
        <div class="separator-fields"></div>
      </div>
      <div class="row-input-list">
        <label class="label-form" for="deal_acceptable_price_value"><%= web_ar_t('deal.acceptable_price_value') %></label>
        <div class="value-form"><%= hr_deal_acceptable_price(@deal.acceptable_price) %></div>
      </div>
      <div class="separator-button-input"></div>
      <% if @deal.in_process? %>
      <div class="w-row">
        <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 n-p-l">
          <%= link_to '修改需求', edit_web_deal_path(@deal), class: 'w-button edit-button' %>
        </div>
        <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 n-p-r">
          <%= link_to '删除', [:web, @deal], method: :delete, data: { confirm: '确定要删除吗？' }, class: 'w-button action-button' %>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>
<% content_for :javascript do %>
  <%= javascript_include_tag 'http://res.wx.qq.com/open/js/jweixin-1.0.0.js' %>
  <script>
    jQuery(document).ready(function(){
      <% unless @deal.photographs.blank? %>
      <%= wechat_config_tag(permissions: [:previewImage]) %>
      wx.ready(function() {
        $('.image-thumbnail').on('click', function() {
          wx.previewImage({
            current: $(this).data('origin-url'),
            urls: ['<%= raw(@deal.photographs.map{|photograph| photograph.file.url}.join("', '")) %>']
          });
        });
      });
      <% end %>
      $('.nailthumb-container:last').nailthumb();
    });
  </script>
<% end %>

app/views/web/deals/edit.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title">修改需求</div>
    <a class="w-inline-block navbar-button" href="<%= url_for([:web, @deal]) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
  </div>
</div>
<div class="body padding">
  <div class="w-form">
    <%= render "web/commons/error_messages", target: @deal %>
    <%= form_for [:web, @deal] do |f| %>
      <div class="separator-fields"></div>
      <div class="separator-fields"></div>
      <div class="row-input-list">
        <label class="label-form" for="deal_content"><%= web_ar_t('deal.content') %></label>
        <textarea id="deal_content" name="deal[content]" class="w-input input-form textarea"><%= @deal.content %></textarea>
        <div class="separator-fields"></div>
      </div>
      <% unless @deal.photographs.blank? %>
      <div class="row-input-list">
        <label class="label-form" for="deal_content"><%= web_ar_t('deal.photographs') %></label>
        <div class="value-form">
          <p>#暂无修改图片功能</p>
          <p>#给您造成的不便敬请谅解</p>
        </div>
        <div class="separator-fields"></div>
      </div>
      <% end %>
      <div class="row-input-list">
        <label class="label-form" for="deal_expected_quantity"><%= web_ar_t('deal.expected_quantity') %></label>
        <select id="deal_expected_quantity" name="deal[expected_quantity]" class="w-select input-form select">
          <% 1.upto(99).each do |expected_quantity| %>
          <option value="<%= expected_quantity %>"<%= ' selected' if @deal.expected_quantity == expected_quantity %>><%= expected_quantity %>件</option>
          <% end %>
        </select>
        <div class="separator-fields"></div>
      </div>
      <div class="row-input-list">
        <label class="label-form" for="deal_acceptable_price_value"><%= web_ar_t('deal.acceptable_price_value') %></label>
        <div class="w-row">
          <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 n-p-l">
            <input type="text" id="deal_acceptable_price_value" name="deal[acceptable_price_value]" data-name="deal_acceptable_price_value" value="<%= @deal.acceptable_price.try(:in_foreign) || @deal.acceptable_price.try(:in_local) %>" class="w-input input-form">
          </div>
          <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 n-p-r">
            <select id="deal_acceptable_price_currency_id" name="deal[acceptable_price_currency_id]" class="w-select input-form select">
              <option value=""<%= ' selected' if @deal.acceptable_price.blank? %>>元(CNY)</option>
              <% Currency.circulation_in(@deal.travel.destinations).each do |currency| %>
              <option value="<%= currency.id %>"<%= ' selected' if @deal.acceptable_price.try(:currency).try(:id) == currency.id %>><%= currency.name_with_code %></option>
              <% end %>
            </select>
          </div>
          <p class="n-p-l"><span class="icon ion-information-circled"> 您能接受的最高价格，留空则表示对价格无要求</span></p>
        </div>
      </div>
      <div class="separator-button-input"></div>
      <input type="submit" value="填写完成，提交" data-wait="请稍候..." class="w-button action-button"> 
    <% end %>
  </div>
</div>

app/views/web/deals/others_show.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title">需求详情</div>
    <a class="w-inline-block navbar-button" href="<%= url_for([:web, @deal.travel]) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
  </div>
</div>
<div class="body padding">
  <div class="w-form">
    <%= render "web/commons/error_messages", target: @deal %>
    <%= form_tag nil do %>
      <div class="separator-fields"></div>
      <div class="separator-fields"></div>
      <div class="row-input-list">
        <label class="label-form" for="deal_content"><%= web_ar_t('deal.content') %></label>
        <div class="value-form"><%= @deal.content %></div>
        <div class="separator-fields"></div>
      </div>
      <% unless @deal.photographs.blank? %>
      <div class="row-input-list">
        <label class="label-form" for="deal_quantity"><%= web_ar_t('deal.photographs') %></label>
        <div class="value-form">
          <div class="image-preview">
            <% @deal.photographs.each do |photograph| %>
            <div class="nailthumb-container image-thumbnail" data-origin-url="<%= photograph.file.url %>"><%= image_tag(photograph.file.w100_h100_fl_q60.url) %></div>
            <% end %>
          </div>
        </div>
        <div class="separator-fields"></div>
      </div>
      <% end %>
      <div class="row-input-list">
        <label class="label-form" for="deal_quantity"><%= web_ar_t('deal.quantity') %></label>
        <div class="value-form"><%= @deal.quantity %>件</div>
        <div class="separator-fields"></div>
      </div>
      <div class="row-input-list">
        <label class="label-form" for="deal_acceptable_price_value"><%= web_ar_t('deal.acceptable_price_value') %></label>
        <div class="value-form"><%= hr_deal_acceptable_price(@deal.acceptable_price, with_local: true) %></div>
      </div>
      <div class="separator-button-input"></div>
      <div class="w-row">
        <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 n-p-l">
          <%= link_to '确认购买', finish_web_deal_path(@deal), method: :put, data: { confirm: '确认买到了商品吗？' }, class: 'w-button edit-button' %>
        </div>
        <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 n-p-r">
          <%= link_to '确认无货', abort_web_deal_path(@deal), method: :put, data: { confirm: '确认无法购买商品吗？' }, class: 'w-button action-button' %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% content_for :javascript do %>
  <%= javascript_include_tag 'http://res.wx.qq.com/open/js/jweixin-1.0.0.js' %>
  <script>
    jQuery(document).ready(function(){
      <% unless @deal.photographs.blank? %>
      <%= wechat_config_tag(permissions: [:previewImage]) %>
      wx.ready(function() {
        $('.image-thumbnail').on('click', function() {
          wx.previewImage({
            current: $(this).data('origin-url'),
            urls: ['<%= raw(@deal.photographs.map{|photograph| photograph.file.url}.join("', '")) %>']
          });
        });
      });
      <% end %>
      $('.nailthumb-container:last').nailthumb();
    });
  </script>
<% end %>

app/views/web/deals/owned.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title">我的需求</div>
    <a class="w-inline-block navbar-button" href="<%= url_for(web_home_path) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
  </div>
</div>
<div class="body">
  <div class="w-clearfix travel-deals-list padding">
    <% if @deals.blank? %>
    <div class="blank-notice"><p>清单是空的哦！</p></div>
    <% else %>
    <ul class="list list-events">
      <% @deals.each do |deal| %>
      <li class="list-calendar-events" data-ix="list-item">
        <a class="w-clearfix w-inline-block" href="<%= url_for(web_deal_path(deal, from: 'owned_deals'))%>" data-load="1">
          <div class="calendar-col-left">
            <div class="event-title"><%= deal.content %></div>
            <div class="w-clearfix text-event-wrap">
              <% if deal.in_process? %>
              <div class="left-text-icon icon ion-clock"></div>
              <div class="event-text">购物中</div>
              <% elsif deal.success? %>
              <div class="left-text-icon icon ion-checkmark-round text-success"></div>
              <div class="event-text text-success">已购买</div>
              <% elsif deal.failure? %>
              <div class="left-text-icon icon ion-close-round text-failure"></div>
              <div class="event-text text-failure">未购买</div>
              <% end %>
            </div>
          </div>
        </a>
      </li>
      <% end %>
    </ul>
    <% end %>
  </div>
</div>

app/views/web/deals/owned_show.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title">需求详情</div>
    <a class="w-inline-block navbar-button" href="<%= url_for([:web, @deal.travel]) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
  </div>
</div>
<div class="body padding">
  <div class="w-form">
    <%= render "web/commons/error_messages", target: @deal %>
    <%= form_tag nil do %>
      <div class="separator-fields"></div>
      <div class="separator-fields"></div>
      <div class="row-input-list">
        <label class="label-form" for="deal_content"><%= web_ar_t('deal.content') %></label>
        <div class="value-form"><%= @deal.content %></div>
        <div class="separator-fields"></div>
      </div>
      <% unless @deal.photographs.blank? %>
      <div class="row-input-list">
        <label class="label-form" for="deal_quantity"><%= web_ar_t('deal.photographs') %></label>
        <div class="value-form">
          <div class="image-preview">
            <% @deal.photographs.each do |photograph| %>
            <div class="nailthumb-container image-thumbnail"><%= image_tag(photograph.file.w100_h100_fl_q60.url) %></div>
            <% end %>
          </div>
        </div>
        <div class="separator-fields"></div>
      </div>
      <% end %>
      <div class="row-input-list">
        <label class="label-form" for="deal_quantity"><%= web_ar_t('deal.quantity') %></label>
        <div class="value-form"><%= @deal.quantity %>件</div>
        <div class="separator-fields"></div>
      </div>
      <div class="row-input-list">
        <label class="label-form" for="deal_acceptable_price_value"><%= web_ar_t('deal.acceptable_price_value') %></label>
        <div class="value-form"><%= hr_deal_acceptable_price(@deal.acceptable_price) %></div>
      </div>
      <div class="separator-button-input"></div>
      <div class="w-row">
        <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 n-p-l">
          <%= link_to '修改需求', edit_web_deal_path(@deal), class: 'w-button edit-button' %>
        </div>
        <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 n-p-r">
          <%= link_to '删除', [:web, @deal], method: :delete, data: { confirm: '确定要删除吗？' }, class: 'w-button action-button' %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% content_for :javascript do %>
  <script>
    jQuery(document).ready(function(){
      $('.nailthumb-container:last').nailthumb();
    });
  </script>
<% end %>

app/views/web/deals/traveller_show.html.erb
<div class="w-nav navbar" data-collapse="all" data-animation="over-left" data-duration="400" data-contain="1" data-easing="ease-out-quint" data-no-scroll="1">
  <div class="w-container">
    <div class="wrapper-mask" data-ix="menu-mask"></div>
    <div class="navbar-title">需求详情</div>
    <a class="w-inline-block navbar-button" href="<%= url_for([:web, @deal.travel]) %>" data-load="1">
      <div class="navbar-button-icon icon ion-ios-arrow-left"></div>
    </a>
  </div>
</div>
<div class="body padding">
  <div class="w-form">
    <%= render "web/commons/error_messages", target: @deal %>
    <%= form_tag nil do %>
      <div class="separator-fields"></div>
      <div class="separator-fields"></div>
      <div class="row-input-list">
        <label class="label-form" for="deal_content"><%= web_ar_t('deal.user') %></label>
        <div class="value-form"><%= image_tag(@deal.user.portrait.w100_h100_fl_q60.url, class: 'portrait') %><%= @deal.user.nickname %></div>
        <div class="separator-fields"></div>
      </div>
      <div class="row-input-list">
        <label class="label-form" for="deal_content"><%= web_ar_t('deal.content') %></label>
        <div class="value-form"><%= @deal.content %></div>
        <div class="separator-fields"></div>
      </div>
      <% unless @deal.photographs.blank? %>
      <div class="row-input-list">
        <label class="label-form" for="deal_expected_quantity"><%= web_ar_t('deal.photographs') %></label>
        <div class="value-form">
          <div class="image-preview">
            <% @deal.photographs.each do |photograph| %>
            <div class="nailthumb-container image-thumbnail" data-origin-url="<%= photograph.file.url %>"><%= image_tag(photograph.file.w100_h100_fl_q60.url) %></div>
            <% end %>
          </div>
        </div>
        <div class="separator-fields"></div>
      </div>
      <% end %>
      <div class="row-input-list">
        <label class="label-form" for="deal_expected_quantity"><%= web_ar_t('deal.expected_quantity') %></label>
        <div class="value-form"><%= @deal.expected_quantity %>件</div>
        <div class="separator-fields"></div>
      </div>
      <div class="row-input-list">
        <label class="label-form" for="deal_acceptable_price_value"><%= web_ar_t('deal.acceptable_price_value') %></label>
        <div class="value-form"><%= hr_deal_acceptable_price(@deal.acceptable_price, with_local: true) %></div>
        <div class="separator-fields"></div>
      </div>
      <% if @deal.in_process? %>
      <div class="separator-button-input"></div>
      <div class="w-row">
        <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 n-p-l">
          <%= link_to '确认购买', buy_form_web_deal_path(@deal), class: 'w-button edit-button' %>
        </div>
        <div class="w-col w-col-6 w-col-small-6 w-col-tiny-6 n-p-r">
          <%= link_to '确认无货', abort_web_deal_path(@deal), method: :put, data: { confirm: '确认无法购买商品吗？' }, class: 'w-button action-button' %>
        </div>
      </div>
      <% elsif @deal.success? %>
      <div class="row-input-list">
        <label class="label-form" for="deal_expected_quantity"><%= web_ar_t('deal.actual_quantity') %></label>
        <div class="value-form"><%= @deal.actual_quantity %>件</div>
        <div class="separator-fields"></div>
      </div>
      <div class="row-input-list">
        <label class="label-form" for="deal_acceptable_price_value"><%= web_ar_t('deal.actual_price_value') %></label>
        <div class="value-form"><%= hr_deal_acceptable_price(@deal.actual_price, with_local: true) %></div>
        <div class="separator-fields"></div>
      </div>
      <%= link_to '返回', [:web, @deal.travel], disabled: true, class: 'w-button edit-button' %>
      <% elsif @deal.failure? %>

      <% end %>
    <% end %>
  </div>
</div>
<% content_for :javascript do %>
  <%= javascript_include_tag 'http://res.wx.qq.com/open/js/jweixin-1.0.0.js' %>
  <script>
    jQuery(document).ready(function(){
      <% unless @deal.photographs.blank? %>
      <%= wechat_config_tag(permissions: [:previewImage]) %>
      wx.ready(function() {
        $('.image-thumbnail').on('click', function() {
          wx.previewImage({
            current: $(this).data('origin-url'),
            urls: ['<%= raw(@deal.photographs.map{|photograph| photograph.file.url}.join("', '")) %>']
          });
        });
      });
      <% end %>
      $('.nailthumb-container:last').nailthumb();
    });
  </script>
<% end %>